import { PrismaClient, Prisma } from "./generated/prisma/client";

const prisma = new PrismaClient();

const userData: Prisma.UnitCreateInput[] = [
  /* Add your seed data here */
  { name: "Patricia", class: "CLERIC", gender: "FEMALE" },
  { name: "Aiden", class: "WARRIOR", gender: "MALE" },
  { name: "Luna", class: "MAGE", gender: "FEMALE" },
  { name: "Kai", class: "ROGUE", gender: "MALE" },
  { name: "Maya", class: "ARCHER", gender: "FEMALE" },
  { name: "Ethan", class: "WARRIOR", gender: "MALE" },
  { name: "Zoe", class: "MAGE", gender: "FEMALE" },
  { name: "Leo", class: "WARRIOR", gender: "MALE" },
  { name: "Ivy", class: "MAGE", gender: "FEMALE" },
  { name: "Noah", class: "MAGE", gender: "MALE" },
  { name: "Aria", class: "CLERIC", gender: "FEMALE" },
  { name: "Owen", class: "ROGUE", gender: "MALE" },
  { name: "Nora", class: "ARCHER", gender: "FEMALE" },
  { name: "Lucas", class: "WARRIOR", gender: "MALE" },
  { name: "Ruby", class: "MAGE", gender: "FEMALE" },
  { name: "Mason", class: "WARRIOR", gender: "MALE" },
  { name: "Ava", class: "MAGE", gender: "FEMALE" },
  { name: "Caleb", class: "ROGUE", gender: "MALE" },
  { name: "Iris", class: "MAGE", gender: "FEMALE" },
  { name: "Jack", class: "WARRIOR", gender: "MALE" },
  { name: "Willow", class: "CLERIC", gender: "FEMALE" },
  { name: "Henry", class: "WARRIOR", gender: "MALE" },
  { name: "Stella", class: "MAGE", gender: "FEMALE" },
  { name: "Julian", class: "MAGE", gender: "MALE" },
  { name: "Lily", class: "ARCHER", gender: "FEMALE" },
  { name: "Thomas", class: "WARRIOR", gender: "MALE" },
  { name: "Chloe", class: "ROGUE", gender: "FEMALE" },
  { name: "Sebastian", class: "WARRIOR", gender: "MALE" },
  { name: "Penelope", class: "CLERIC", gender: "FEMALE" },
  { name: "Daniel", class: "MAGE", gender: "MALE" },
  { name: "Grace", class: "MAGE", gender: "FEMALE" },
  { name: "Leo2", class: "WARRIOR", gender: "MALE" },
  { name: "Hazel", class: "MAGE", gender: "FEMALE" },
  { name: "Isaac", class: "ROGUE", gender: "MALE" },
  { name: "Audrey", class: "ARCHER", gender: "FEMALE" },
  { name: "David", class: "WARRIOR", gender: "MALE" },
  { name: "Bella", class: "MAGE", gender: "FEMALE" },
  { name: "Ryan", class: "WARRIOR", gender: "MALE" },
  { name: "Eva", class: "CLERIC", gender: "FEMALE" },
  { name: "Connor", class: "MAGE", gender: "MALE" },
  { name: "Sofia", class: "ROGUE", gender: "FEMALE" },
  { name: "Wyatt", class: "ARCHER", gender: "MALE" },
  { name: "Mila", class: "MAGE", gender: "FEMALE" },
  { name: "Eli", class: "WARRIOR", gender: "MALE" },
  { name: "Lucy", class: "MAGE", gender: "FEMALE" },
  { name: "Gabriel", class: "WARRIOR", gender: "MALE" },
  { name: "Anna", class: "CLERIC", gender: "FEMALE" },
  { name: "Aaron", class: "MAGE", gender: "MALE" },
  { name: "Zara", class: "ROGUE", gender: "FEMALE" },
  { name: "Cole", class: "WARRIOR", gender: "MALE" },
  { name: "Ivy2", class: "MAGE", gender: "FEMALE" },
  { name: "Evan", class: "ARCHER", gender: "MALE" },
  { name: "Maya2", class: "MAGE", gender: "FEMALE" },
  { name: "Blake", class: "WARRIOR", gender: "MALE" },
  { name: "Leah", class: "CLERIC", gender: "FEMALE" },
  { name: "Omar", class: "ROGUE", gender: "MALE" },
  { name: "Nina", class: "MAGE", gender: "FEMALE" },
  { name: "Victor", class: "WARRIOR", gender: "MALE" },
  { name: "Cora", class: "MAGE", gender: "FEMALE" },
  { name: "Miles", class: "ARCHER", gender: "MALE" },
  { name: "Daisy", class: "MAGE", gender: "FEMALE" },
  { name: "Adrian", class: "WARRIOR", gender: "MALE" },
  { name: "Faith", class: "CLERIC", gender: "FEMALE" },
  { name: "Jasper", class: "ROGUE", gender: "MALE" },
  { name: "Ruby2", class: "MAGE", gender: "FEMALE" },
  { name: "Ezekiel", class: "MAGE", gender: "MALE" },
  { name: "Olive", class: "MAGE", gender: "FEMALE" },
  { name: "Silas", class: "WARRIOR", gender: "MALE" },
  { name: "Maya3", class: "CLERIC", gender: "FEMALE" },
  { name: "Toby", class: "WARRIOR", gender: "MALE" },
  { name: "Hope", class: "MAGE", gender: "FEMALE" },
  { name: "Finn", class: "ROGUE", gender: "MALE" },
  { name: "Cecilia", class: "MAGE", gender: "FEMALE" },
  { name: "Reed", class: "ARCHER", gender: "MALE" },
  { name: "June", class: "MAGE", gender: "FEMALE" },
  { name: "Gavin", class: "WARRIOR", gender: "MALE" },
  { name: "Iris2", class: "CLERIC", gender: "FEMALE" },
  { name: "Odin", class: "WARRIOR", gender: "MALE" },
  { name: "Paige", class: "MAGE", gender: "FEMALE" },
  { name: "Quinn", class: "ROGUE", gender: "MALE" },
  { name: "Raine", class: "MAGE", gender: "FEMALE" },
  { name: "Saul", class: "WARRIOR", gender: "MALE" },
  { name: "Tessa", class: "MAGE", gender: "FEMALE" },
  { name: "Ulysses", class: "ARCHER", gender: "MALE" },
  { name: "Vera", class: "CLERIC", gender: "FEMALE" },
  { name: "Wesley", class: "WARRIOR", gender: "MALE" },
  { name: "Xena", class: "MAGE", gender: "FEMALE" },
  { name: "Yosef", class: "ROGUE", gender: "MALE" },
  { name: "Zelda", class: "MAGE", gender: "FEMALE" },
  { name: "Ari", class: "WARRIOR", gender: "MALE" },
  { name: "Bryn", class: "MAGE", gender: "FEMALE" },
  { name: "Cade", class: "WARRIOR", gender: "MALE" },
  { name: "Delta", class: "MAGE", gender: "FEMALE" },
  { name: "Emmett", class: "ROGUE", gender: "MALE" },
  { name: "Freya", class: "MAGE", gender: "FEMALE" },
  { name: "Gideon", class: "WARRIOR", gender: "MALE" },
  { name: "Hana", class: "CLERIC", gender: "FEMALE" },
  { name: "Ivan", class: "ARCHER", gender: "MALE" },
  { name: "Juno", class: "MAGE", gender: "FEMALE" },
  { name: "Kane", class: "WARRIOR", gender: "MALE" },
  { name: "Lara", class: "MAGE", gender: "FEMALE" },
  { name: "Milo", class: "ROGUE", gender: "MALE" },
  { name: "Nell", class: "MAGE", gender: "FEMALE" },
  { name: "Otis", class: "WARRIOR", gender: "MALE" },
  { name: "Poppy", class: "CLERIC", gender: "FEMALE" },
  { name: "Rex", class: "WARRIOR", gender: "MALE" },
  { name: "Sage", class: "MAGE", gender: "FEMALE" },
  { name: "Theo", class: "ARCHER", gender: "MALE" },
  { name: "Uma", class: "MAGE", gender: "FEMALE" },
  { name: "Vox", class: "ROGUE", gender: "MALE" },
  { name: "Wynn", class: "MAGE", gender: "FEMALE" },
  { name: "Yara", class: "CLERIC", gender: "FEMALE" },
  { name: "Zane", class: "WARRIOR", gender: "MALE" },
];

export async function main() {
  for (const u of userData) {
    await prisma.unit.create({ data: u });
  }
}

main();
